# Test fixtures are not production code; skip analysis.
sonar.exclusions=prepare-sources/**/__fixtures__/**/*
# Code duplication detection usually doesn't make sense in test files.
sonar.cpd.exclusions=prepare-sources/lib/**/*.test.ts
