import { describe, expect, it } from "vitest";
import {
  type Lockfile,
  type LockfileBlock,
  getMap,
  getNestedMap,
  getScalar,
  parseLockfile,
  serializeBlock,
  serializeLockfile,
} from "./yarn-lock-parser.ts";

function roundTrip(lockfile: Lockfile): string {
  return serializeLockfile(lockfile);
}

function expectFirstBlock(lockfile: Lockfile): LockfileBlock {
  const block = lockfile.blocks[0];
  expect(block).toBeDefined();
  if (!block) {
    throw new Error("expected block");
  }
  return block;
}

// ---------------------------------------------------------------------------
// Round-trip fidelity
// ---------------------------------------------------------------------------

describe("round-trip fidelity", () => {
  const cases: [string, string][] = [
    [
      "simple lockfile",
      [
        '# This file is generated by running "yarn install" inside your project.',
        "# Manual changes might be lost - proceed with caution!",
        "",
        "__metadata:",
        "  version: 8",
        "  cacheKey: 10c0",
        "",
        '"@backstage/core-plugin-api@backstage:^":',
        "  version: 1.10.9",
        '  resolution: "@backstage/core-plugin-api@npm:1.10.9"',
        "  dependencies:",
        '    "@backstage/types": "npm:^1.2.3"',
        '    react: "npm:^18.0.0"',
        "  checksum: abc123",
        "  languageName: node",
        "  linkType: hard",
        "",
      ].join("\n"),
    ],
    [
      "combined keys",
      [
        "__metadata:",
        "  version: 8",
        "",
        '"@aws-sdk/types@npm:^3.222.0, @aws-sdk/types@npm:^3.347.0, @aws-sdk/types@npm:^3.973.1":',
        "  version: 3.973.1",
        '  resolution: "@aws-sdk/types@npm:3.973.1"',
        "  checksum: abc",
        "",
      ].join("\n"),
    ],
    [
      "nested map (peerDependenciesMeta)",
      [
        "__metadata:",
        "  version: 8",
        "",
        '"@backstage/theme@backstage:^":',
        "  version: 0.6.3",
        "  peerDependencies:",
        '    react: "npm:^18.0.0"',
        "  peerDependenciesMeta:",
        "    react:",
        "      optional: true",
        "  linkType: hard",
        "",
      ].join("\n"),
    ],
    [
      "unquoted simple keys in deps",
      [
        "__metadata:",
        "  version: 8",
        "",
        '"ajv@npm:^8.17.1":',
        "  version: 8.17.1",
        "  dependencies:",
        '    fast-deep-equal: "npm:^3.1.3"',
        '    json-schema-traverse: "npm:^1.0.0"',
        '    require-from-string: "npm:^2.0.2"',
        '    uri-js: "npm:^4.4.1"',
        "  linkType: hard",
        "",
      ].join("\n"),
    ],
    [
      "workspace block",
      [
        "__metadata:",
        "  version: 8",
        "",
        '"@test/root@workspace:.":',
        "  version: 0.0.0-use.local",
        '  resolution: "@test/root@workspace:."',
        "  languageName: unknown",
        "  linkType: soft",
        "",
      ].join("\n"),
    ],
    [
      "block with bin",
      [
        "__metadata:",
        "  version: 8",
        "",
        '"@backstage/core-plugin-api@backstage:^":',
        "  version: 1.10.9",
        "  bin:",
        "    backstage-core: ./dist/cli.js",
        "  checksum: abc123",
        "",
      ].join("\n"),
    ],
    [
      "multiple blocks",
      [
        "__metadata:",
        "  version: 8",
        "",
        '"pkg-a@npm:^1.0.0":',
        "  version: 1.0.0",
        "  linkType: hard",
        "",
        '"pkg-b@npm:^2.0.0":',
        "  version: 2.0.0",
        "  dependencies:",
        '    pkg-a: "npm:^1.0.0"',
        "  linkType: hard",
        "",
      ].join("\n"),
    ],
  ];

  it.each(cases)("%s", (_name, input) => {
    const lockfile = parseLockfile(input);
    const output = serializeLockfile(lockfile);
    expect(output).toBe(input);
  });
});

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

describe("parseLockfile", () => {
  it("captures the preamble including __metadata", () => {
    const input = [
      "# comment",
      "",
      "__metadata:",
      "  version: 8",
      "  cacheKey: 10c0",
      "",
      '"pkg@npm:^1.0.0":',
      "  version: 1.0.0",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    expect(lockfile.preamble).toBe("# comment\n\n__metadata:\n  version: 8\n  cacheKey: 10c0");
    expect(lockfile.blocks).toHaveLength(1);
  });

  it("handles lockfile without __metadata", () => {
    const input = ['"pkg@npm:^1.0.0":', "  version: 1.0.0", ""].join("\n");

    const lockfile = parseLockfile(input);
    expect(lockfile.preamble).toBe("");
    expect(lockfile.blocks).toHaveLength(1);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.version).toEqual({
      kind: "scalar",
      raw: "1.0.0",
    });
  });

  it("parses combined descriptor keys", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"@aws/types@npm:^3.0.0, @aws/types@npm:^3.1.0":',
      "  version: 3.1.0",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.descriptors).toEqual(["@aws/types@npm:^3.0.0", "@aws/types@npm:^3.1.0"]);
  });

  it("parses scalar, map, and nested-map fields", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"@backstage/theme@backstage:^":',
      "  version: 0.6.3",
      '  resolution: "@backstage/theme@npm:0.6.3"',
      "  dependencies:",
      '    "@emotion/react": "npm:^11.0.0"',
      "  peerDependencies:",
      '    react: "npm:^18.0.0"',
      "  peerDependenciesMeta:",
      "    react:",
      "      optional: true",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);

    expect(block.fields.version).toEqual({ kind: "scalar", raw: "0.6.3" });
    expect(block.fields.resolution).toEqual({
      kind: "scalar",
      raw: '"@backstage/theme@npm:0.6.3"',
    });
    expect(block.fields.dependencies).toEqual({
      kind: "map",
      entries: { '"@emotion/react"': '"npm:^11.0.0"' },
    });
    expect(block.fields.peerDependencies).toEqual({
      kind: "map",
      entries: { react: '"npm:^18.0.0"' },
    });
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { optional: "true" } },
    });
    expect(block.fields.linkType).toEqual({ kind: "scalar", raw: "hard" });
  });

  it("skips blank lines between blocks", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      "",
      '"a@npm:1":',
      "  version: 1",
      "",
      "",
      "",
      '"b@npm:2":',
      "  version: 2",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    expect(lockfile.blocks).toHaveLength(2);
  });

  it("skips stray non-descriptor lines", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      "this is a stray line without trailing colon",
      "",
      '"pkg@npm:1":',
      "  version: 1",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    expect(lockfile.blocks).toHaveLength(1);
    const block = expectFirstBlock(lockfile);
    expect(block.descriptors).toEqual(["pkg@npm:1"]);
  });

  it("handles unquoted descriptor (non-standard)", () => {
    const input = ["my-pkg@npm:1.0.0:", "  version: 1.0.0", ""].join("\n");

    const lockfile = parseLockfile(input);
    expect(lockfile.blocks).toHaveLength(1);
    const block = expectFirstBlock(lockfile);
    expect(block.descriptors).toEqual(["my-pkg@npm:1.0.0"]);
  });

  it("skips mid-file comment lines", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      "# Inline comment between blocks",
      '"pkg@npm:1":',
      "  version: 1",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    expect(lockfile.blocks).toHaveLength(1);
  });

  it("handles nested-map with orphan property before key", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"pkg@npm:1":',
      "  version: 1",
      "  peerDependenciesMeta:",
      "      orphan: true",
      "    react:",
      "      optional: true",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { optional: "true" } },
    });
    expect(block.fields.linkType).toEqual({ kind: "scalar", raw: "hard" });
  });
});

// ---------------------------------------------------------------------------
// Serialization
// ---------------------------------------------------------------------------

describe("serializeBlock", () => {
  it("quotes all descriptors", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:^1.0.0"],
      fields: { version: { kind: "scalar", raw: "1.0.0" } },
    };
    const output = serializeBlock(block);
    expect(output).toBe('"pkg@npm:^1.0.0":\n  version: 1.0.0');
  });

  it("serializes combined descriptors within one pair of quotes", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:^1.0.0", "pkg@npm:^1.1.0"],
      fields: { version: { kind: "scalar", raw: "1.1.0" } },
    };
    const output = serializeBlock(block);
    expect(output.startsWith('"pkg@npm:^1.0.0, pkg@npm:^1.1.0":')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Convenience accessors
// ---------------------------------------------------------------------------

describe("getScalar", () => {
  it("returns unquoted value", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:1"],
      fields: {
        version: { kind: "scalar", raw: "1.0.0" },
        resolution: { kind: "scalar", raw: '"pkg@npm:1.0.0"' },
      },
    };
    expect(getScalar(block, "version")).toBe("1.0.0");
    expect(getScalar(block, "resolution")).toBe("pkg@npm:1.0.0");
  });

  it("returns undefined for missing or non-scalar field", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:1"],
      fields: {
        deps: { kind: "map", entries: { a: "1" } },
      },
    };
    expect(getScalar(block, "missing")).toBeUndefined();
    expect(getScalar(block, "deps")).toBeUndefined();
  });
});

describe("getMap", () => {
  it("returns entries", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:1"],
      fields: {
        dependencies: {
          kind: "map",
          entries: { react: '"npm:^18.0.0"' },
        },
      },
    };
    expect(getMap(block, "dependencies")).toEqual({
      react: '"npm:^18.0.0"',
    });
  });

  it("returns undefined for missing or non-map field", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:1"],
      fields: {
        version: { kind: "scalar", raw: "1" },
      },
    };
    expect(getMap(block, "missing")).toBeUndefined();
    expect(getMap(block, "version")).toBeUndefined();
  });
});

describe("getNestedMap", () => {
  it("returns entries", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:1"],
      fields: {
        peerDependenciesMeta: {
          kind: "nested-map",
          entries: { react: { optional: "true" } },
        },
      },
    };
    expect(getNestedMap(block, "peerDependenciesMeta")).toEqual({
      react: { optional: "true" },
    });
  });

  it("returns undefined for missing or non-nested-map field", () => {
    const block: LockfileBlock = {
      descriptors: ["pkg@npm:1"],
      fields: {
        version: { kind: "scalar", raw: "1" },
      },
    };
    expect(getNestedMap(block, "missing")).toBeUndefined();
    expect(getNestedMap(block, "version")).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// Mutation scenarios (for protocol-resolution)
// ---------------------------------------------------------------------------

describe("mutation", () => {
  it("allows updating a scalar value while preserving order", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"pkg@npm:^1.0.0":',
      "  version: 1.0.0",
      '  resolution: "pkg@npm:1.0.0"',
      "  checksum: abc",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    block.fields.version = { kind: "scalar", raw: "2.0.0" };

    expect(roundTrip(lockfile)).toBe(input.replace("version: 1.0.0", "version: 2.0.0"));
  });

  it("allows replacing a dependency value in a map", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"pkg@npm:^1.0.0":',
      "  version: 1.0.0",
      "  dependencies:",
      '    react: "npm:^17.0.0"',
      '    lodash: "npm:^4.0.0"',
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    const deps = block.fields.dependencies;
    if (deps?.kind === "map") {
      deps.entries.react = '"npm:^18.0.0"';
    }

    const output = roundTrip(lockfile);
    expect(output).toContain('react: "npm:^18.0.0"');
    expect(output).toContain('lodash: "npm:^4.0.0"');
    expect(output.indexOf("react")).toBeLessThan(output.indexOf("lodash"));
  });

  it("allows adding a new block", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"pkg-a@npm:^1.0.0":',
      "  version: 1.0.0",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    lockfile.blocks.push({
      descriptors: ["pkg-b@npm:^2.0.0"],
      fields: {
        version: { kind: "scalar", raw: "2.0.0" },
        linkType: { kind: "scalar", raw: "hard" },
      },
    });

    const output = roundTrip(lockfile);
    expect(output).toContain('"pkg-b@npm:^2.0.0":');
    expect(output).toContain("version: 2.0.0");
  });

  it("allows removing a block", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"pkg-a@npm:^1.0.0":',
      "  version: 1.0.0",
      "",
      '"pkg-b@npm:^2.0.0":',
      "  version: 2.0.0",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    lockfile.blocks = lockfile.blocks.filter((b) => {
      const firstDescriptor = b.descriptors[0];
      return firstDescriptor === undefined || !firstDescriptor.includes("pkg-b");
    });

    const output = roundTrip(lockfile);
    expect(output).toContain("pkg-a");
    expect(output).not.toContain("pkg-b");
  });

  it("allows enriching descriptors (adding a specifier)", () => {
    const input = [
      "__metadata:",
      "  version: 8",
      "",
      '"@backstage/core@backstage:^":',
      "  version: 1.0.0",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    block.descriptors.push("@backstage/core@npm:1.0.0");

    const output = roundTrip(lockfile);
    expect(output).toContain('"@backstage/core@backstage:^, @backstage/core@npm:1.0.0":');
  });
});

// ---------------------------------------------------------------------------
// Edge cases: defensive branches
// ---------------------------------------------------------------------------

describe("parser edge cases", () => {
  it("stops parsing block body on an empty line", () => {
    const input = ['"pkg@npm:1":', "  version: 1.0.0", "", "  linkType: hard", ""].join("\n");

    const lockfile = parseLockfile(input);
    expect(lockfile.blocks).toHaveLength(1);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.version).toEqual({
      kind: "scalar",
      raw: "1.0.0",
    });
    expect(block.fields.linkType).toBeUndefined();
  });

  it("stops parsing block body on a 2-space line that is not a valid field", () => {
    const input = [
      '"pkg@npm:1":',
      "  version: 1.0.0",
      "  no-colon-here",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.version).toBeDefined();
    expect(block.fields.linkType).toBeUndefined();
  });

  it("handles a section header with no sub-content", () => {
    const input = [
      '"pkg@npm:1":',
      "  version: 1.0.0",
      "  dependencies:",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.dependencies).toBeUndefined();
    expect(block.fields.linkType).toEqual({ kind: "scalar", raw: "hard" });
  });

  it("skips malformed 4-space map entries", () => {
    const input = [
      '"pkg@npm:1":',
      "  version: 1.0.0",
      "  dependencies:",
      "    valid-dep: 1.0.0",
      "    no-colon-garbage",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.dependencies).toEqual({
      kind: "map",
      entries: { "valid-dep": "1.0.0" },
    });
  });

  it("skips malformed 6-space nested-map property lines", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    react:",
      "      optional: true",
      "      garbage-no-colon",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { optional: "true" } },
    });
  });

  it("breaks nested-map on a 4-space line that is not a key header", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    react:",
      "      optional: true",
      "    not-a-key-header 1.0.0",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { optional: "true" } },
    });
  });

  it("stops parsing on degenerate field lines with empty name", () => {
    const input = [
      '"pkg@npm:1":',
      "  version: 1.0.0",
      "  : orphan-value",
      "  :",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.version).toBeDefined();
    expect(block.fields[""]).toBeUndefined();
    expect(block.fields.linkType).toBeUndefined();
  });

  it("stops parsing on field lines with colon not followed by whitespace", () => {
    const input = [
      '"pkg@npm:1":',
      "  version: 1.0.0",
      "  name:value-no-space",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.version).toBeDefined();
    expect(block.fields.name).toBeUndefined();
    expect(block.fields.linkType).toBeUndefined();
  });

  it("handles map keys containing colons", () => {
    const input = [
      '"pkg@npm:1":',
      "  dependencies:",
      '    "key:with:colons": "npm:^1.0.0"',
      "    simple-key: value",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.dependencies).toEqual({
      kind: "map",
      entries: {
        '"key:with:colons"': '"npm:^1.0.0"',
        "simple-key": "value",
      },
    });
  });

  it("handles nested-map keys containing colons", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    key:sub:",
      "      optional: true",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { "key:sub": { optional: "true" } },
    });
  });

  it("handles nested-map property names containing colons", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    react:",
      "      prop:name: true",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { "prop:name": "true" } },
    });
  });

  it("drops orphan 4-space line that appears before any field header", () => {
    const input = ['"pkg@npm:1":', "    orphan-deep-line: value", "  version: 1.0.0", ""].join(
      "\n",
    );

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.version).toEqual({ kind: "scalar", raw: "1.0.0" });
  });

  it("stops block parsing on stray non-indented line before first field", () => {
    const input = ['"pkg@npm:1":', "stray-line-at-top", "  version: 1.0.0", ""].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.version).toBeUndefined();
  });

  it("stops block parsing on stray non-indented line inside a map section", () => {
    const input = [
      '"pkg@npm:1":',
      "  dependencies:",
      "    valid: 1.0.0",
      "stray-line",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.dependencies).toEqual({
      kind: "map",
      entries: { valid: "1.0.0" },
    });
    expect(block.fields.linkType).toBeUndefined();
  });

  it("stops block parsing on stray non-indented line inside a nested-map section", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    react:",
      "      optional: true",
      "stray-line",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { optional: "true" } },
    });
    expect(block.fields.linkType).toBeUndefined();
  });

  it("does not misidentify 5-space lines as nested-map headers", () => {
    const input = [
      '"pkg@npm:1":',
      "  section:",
      "     five-space-key: value",
      "    normal-key: value",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    // 5-space line is NOT a nested-map header → section is parsed as flat map
    expect(block.fields.section).toEqual({
      kind: "map",
      entries: { " five-space-key": "value", "normal-key": "value" },
    });
  });

  it("skips map entries with empty key (colon at indent boundary)", () => {
    const input = [
      '"pkg@npm:1":',
      "  dependencies:",
      "    : empty-key-value",
      "    valid: 1.0.0",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.dependencies).toEqual({
      kind: "map",
      entries: { valid: "1.0.0" },
    });
  });

  it("skips nested-map key headers with empty key", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    :",
      "      optional: true",
      "    react:",
      "      optional: false",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { optional: "false" } },
    });
  });

  it("skips nested-map properties with empty prop name", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    react:",
      "      : empty-prop-value",
      "      optional: true",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: { react: { optional: "true" } },
    });
  });

  it("produces empty map when all entries are malformed", () => {
    const input = [
      '"pkg@npm:1":',
      "  dependencies:",
      "    no-colon-here",
      "    also-no-colon",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.dependencies).toEqual({
      kind: "map",
      entries: {},
    });
  });

  it("produces empty nested-map when all keys are malformed", () => {
    const input = [
      '"pkg@npm:1":',
      "  peerDependenciesMeta:",
      "    not-a-key-header 1.0.0",
      "      orphan: true",
      "  linkType: hard",
      "",
    ].join("\n");

    const lockfile = parseLockfile(input);
    const block = expectFirstBlock(lockfile);
    expect(block.fields.peerDependenciesMeta).toEqual({
      kind: "nested-map",
      entries: {},
    });
  });

  it("serializes lockfile with empty preamble", () => {
    const lockfile: Lockfile = {
      preamble: "",
      blocks: [
        {
          descriptors: ["pkg@npm:1"],
          fields: { version: { kind: "scalar", raw: "1.0.0" } },
        },
      ],
    };
    const output = serializeLockfile(lockfile);
    expect(output).toBe('\n"pkg@npm:1":\n  version: 1.0.0\n');
  });
});

// ---------------------------------------------------------------------------
// Real-world lockfile round-trip
// ---------------------------------------------------------------------------

describe("real-world fixture round-trip", () => {
  it("round-trips the monorepo-with-backstage fixture", async () => {
    const fs = await import("node:fs");
    const path = await import("node:path");
    const fixturePath = path.join(
      import.meta.dirname,
      "modules/generate-manifests/__fixtures__/monorepo-with-backstage/input/workspace/yarn.lock",
    );
    const content = fs.readFileSync(fixturePath, "utf8");
    const lockfile = parseLockfile(content);
    const output = serializeLockfile(lockfile);
    expect(output).toBe(content);
  });
});
