name: Export to dynamic plugin archives
description: Export plugins to dynamic plugin package archives
inputs:
  plugins-file:
    description: file that contains a yaml dictionary of plugin relative paths to export as dynamic plugins, optionally specifying additional export-dynamic command line arguments.
    required: true

  destination:
    description: Folder that should receive all the targz archives.
    required: false
    default: dynamic-plugins-destination

  janus-cli-version:
    description: Version of the janus-idp/cli package.
    required: false
    default: ^1.8.5

  app-config-file-name:
    description: File name of the app-config files in which we expect to have the default configuration of a frontend plugin.
    required: false
    default: app-config.dynamic.yaml

  scalprum-config-file-name:
    description: File name of the scalprum config JSON files in which we expect to have the optional scalprum configuration of a frontend plugin.
    required: false
    default: scalprum-config.json

  source-overlay-folder-name:
    description: Name of optional sub-folder with files to be applied over the plugin sources before exporting it.
    required: false
    default: overlay

outputs:
  errors:
    description: 'The generated random number'
    value: ${{ steps.run-export-dynamic.outputs.ERRORS }}    

runs:
  using: 'composite'
  steps:
    - name: Run ExportDynamic
      id: run-export-dynamic
      shell: bash
      env:
        NPM_CONFIG_ignore-scripts: 'true'
        YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'
        INPUTS_DESTINATION: '${{ inputs.destination }}'
        INPUTS_JANUS_CLI_VERSION: '${{ inputs.janus-cli-version }}'
        INPUTS_PLUGINS_FILE: '${{ inputs.plugins-file }}'
        INPUTS_APP_CONFIG_FILE_NAME: '${{ inputs.app-config-file-name }}'
        INPUTS_SCALPRUM_CONFIG_FILE_NAME: '${{ inputs.scalprum-config-file-name }}'
        INPUTS_SOURCE_OVERLAY_FOLDER_NAME: '${{ inputs.source-overlay-folder-name }}'
      run: ./export-dynamic.sh
