name: Export to dynamic plugin archives
description: Export plugins to dynamic plugin package archives
inputs:
  plugins-root:
    description: Monorepo root relative folder, in the repository that contains the backstage plugins to be exported as dynamic.
    required: true

  plugins-file:
    description:
      Absolute path of the file that contains a yaml dictionary of plugin relative paths to export as dynamic plugins,
      optionally specifying additional export-dynamic command line arguments.
    required: true

  destination:
    description: Absolute path of the folder that should receive all the targz archives.
    required: false
    default: ""

  janus-cli-version:
    description: Version of the janus-idp/cli package.
    required: false
    default: ^1.8.5

  app-config-file-name:
    description:
      File name of the app-config files in which we expect to have the default configuration of a frontend plugin.
    required: false
    default: app-config.dynamic.yaml

  scalprum-config-file-name:
    description:
      File name of the scalprum config JSON files in which we expect to have the optional scalprum configuration of a
      frontend plugin.
    required: false
    default: scalprum-config.json

  source-overlay-folder-name:
    description: Name of an optional sub-folder with files to be applied over the plugin sources before exporting it.
    required: false
    default: overlay

  source-patch-file-name:
    description: Fine name of an optional patch to be applied over the plugin sources before exporting it.
    required: false
    default: patch

  image-repository-prefix:
    description: Base image name to publish dynamic plugins as container image
    default: ""
    required: false

  image-tag-prefix:
    description: Optional prefix to prepend to the plugin version in the image tag
    default: ""
    required: false

outputs:
  failed-exports:
    description: "Failed exports"
    value: ${{ steps.run-export-dynamic.outputs.FAILED_EXPORTS }}
  published-exports:
    description: "published container images"
    value: ${{ steps.run-export-dynamic.outputs.PUBLISHED_EXPORTS }}

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      uses: actions/github-script@v7
      env:
        INPUT_PLUGINS_ROOT: ${{ inputs.plugins-root }}
      with:
        script: |
          const pluginsRoot = core.getInput('plugins_root');
          if (pluginsRoot.startsWith('/') || pluginsRoot.includes('..')) {
            core.setFailed(`Invalid plugins root: ${pluginsRoot}`);
          }

    - name: Run ExportDynamic
      id: run-export-dynamic
      shell: bash
      working-directory: ${{ inputs.plugins-root }}
      env:
        NPM_CONFIG_ignore-scripts: "true"
        YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
        INPUTS_DESTINATION: "${{ inputs.destination }}"
        INPUTS_JANUS_CLI_VERSION: "${{ inputs.janus-cli-version }}"
        INPUTS_PLUGINS_FILE: "${{ inputs.plugins-file }}"
        INPUTS_APP_CONFIG_FILE_NAME: "${{ inputs.app-config-file-name }}"
        INPUTS_SCALPRUM_CONFIG_FILE_NAME: "${{ inputs.scalprum-config-file-name }}"
        INPUTS_SOURCE_OVERLAY_FOLDER_NAME: "${{ inputs.source-overlay-folder-name }}"
        INPUTS_SOURCE_PATCH_FILE_NAME: "${{ inputs.source-patch-file-name }}"
        INPUTS_IMAGE_REPOSITORY_PREFIX: "${{ inputs.image-repository-prefix }}"
        INPUTS_IMAGE_TAG_PREFIX: "${{ inputs.image-tag-prefix }}"
        INPUTS_PUSH_CONTAINER_IMAGE: "true"
        
      run: ${{ github.action_path }}/export-dynamic.sh
